"""add original invoice field

Revision ID: 0297c48ec3e6
Revises: 4f4e11fa7a48
Create Date: 2025-05-16 23:07:18.539014

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "0297c48ec3e6"
down_revision = "4f4e11fa7a48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_accounts",
        sa.Column(
            "original_payment_request",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_accounts", "original_payment_request")
    # ### end Alembic commands ###
