"""add email password column

Revision ID: 4f4e11fa7a48
Revises: de5e44bb1aae
Create Date: 2025-05-16 18:07:37.366000

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "4f4e11fa7a48"
down_revision = "de5e44bb1aae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_accounts",
        sa.Column("email_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_accounts", "email_password")
    # ### end Alembic commands ###
