"""Initial migration

Revision ID: de5e44bb1aae
Revises:
Create Date: 2025-05-16 15:01:49.309510

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "de5e44bb1aae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("payment_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum("PENDING", "PAID", "EXPIRED", name="paymentstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_accounts_access_token"),
        "email_accounts",
        ["access_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_email_accounts_email_address"),
        "email_accounts",
        ["email_address"],
        unique=True,
    )
    op.create_index(
        op.f("ix_email_accounts_payment_hash"),
        "email_accounts",
        ["payment_hash"],
        unique=False,
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["email_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emails_account_id"), "emails", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_emails_message_id"), "emails", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emails_message_id"), table_name="emails")
    op.drop_index(op.f("ix_emails_account_id"), table_name="emails")
    op.drop_table("emails")
    op.drop_index(op.f("ix_email_accounts_payment_hash"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_email_address"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_access_token"), table_name="email_accounts")
    op.drop_table("email_accounts")
    # ### end Alembic commands ###
